let animels = ["Tiger", "Lion", "Chettas", "Wolvs"];
animels.push("Humming-Bird", "Doyel");
let Birds=["Humming Bird", "Doyel", "Sparrow","Eagle"];
console.log(animels);
animels.pop();
console.log(animels);
animels.shift();
console.log(animels);
animels.unshift("Bangol Tiger", "Dog");
console.log(animels);
animels.splice(2, 1, "Lion");
console.log(animels);
animels.splice(1,1,"Hayenas");
console.log(animels);
console.log("______---_______---__________--____");
animels=animels.concat(Birds);
console.log(animels);
console.log(animels.at(2));
console.log("______---_______---__________--____");
console.log(animels.copyWithin(0, 2 ,4));